import type { LucideIcon } from 'lucide-react'
import {
  ArrowLeftRight,
  Book,
  Briefcase,
  Car,
  Coffee,
  Film,
  Gift,
  Hammer,
  HeartPulse,
  Home,
  Layers,
  PiggyBank,
  Plane,
  Plug,
  Repeat,
  Shirt,
  ShoppingBag,
  Smartphone,
  User,
  Utensils,
  Wallet,
} from 'lucide-react'

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  plug: Plug,
  utensils: Utensils,
  car: Car,
  'heart-pulse': HeartPulse,
  user: User,
  film: Film,
  'shopping-bag': ShoppingBag,
  repeat: Repeat,
  plane: Plane,
  wallet: Wallet,
  'arrow-left-right': ArrowLeftRight,
  layers: Layers,
  briefcase: Briefcase,
  coffee: Coffee,
  gift: Gift,
  shirt: Shirt,
  hammer: Hammer,
  book: Book,
  smartphone: Smartphone,
  'piggy-bank': PiggyBank,
}
